[package]
authors = ["Andrew Smith <andrewchristophersmith@gmail.com>"]
name = "vox_box_supercollider"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
num = "*"
libc = "*"
rand = "*"

[dependencies.vox_box]
path = "../vox_box"
